# ------------------------------------------------------------------------
#
# Copyright 2017 WSO2, Inc. (http://wso2.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License
#
# ------------------------------------------------------------------------

FROM ubuntu:16.04
MAINTAINER WSO2 Docker Maintainers "dev@wso2.org"
ENV DEBIAN_FRONTEND noninteractive

# defined arguments and defaults
ARG USER=wso2user
ARG USER_ID=1000000000
# files
ARG FILES=./files
ARG USER_HOME=/home/${USER}
ARG WSO2_SERVER=wso2am
ARG WSO2_SERVER_VERSION=2.1.0
ARG WSO2_SERVER_PACK=${WSO2_SERVER}-${WSO2_SERVER_VERSION}.zip
ARG JDK_ARCHIVE=jdk-8u*-linux-x64.tar.gz
ARG JAVA_HOME=${USER_HOME}/java
ARG STARTUP_SCRIPT=init_carbon.sh
ARG LIBS=${FILES}/libs/*
ARG PATCHES=${FILES}/patches/*
ARG IN_SEQ=${FILES}/in_seq/*
ARG OUT_SEQ=${FILES}/out_seq/*
ARG FAULT_SEQ=${FILES}/fault_seq/*
ARG WEBAPPS=${FILES}/webapps/*
ARG JAGGERYAPPS=${FILES}/jaggeryapps/*
ARG CLIENT_TRUSTSTORE=client-truststore.jks
ARG WSO2CARBON_JKS=wso2carbon.jks
ARG TARGET_PATCH_DIR=patch001

RUN apt-get update \
	&& apt-get install -y --no-install-recommends --no-install-suggests \
       	   zip \
           unzip \
           telnet \
           iproute2 \
	   sudo && rm -rf /var/lib/apt/lists/*

# creates the user 
RUN useradd --system --uid ${USER_ID} --gid 0 --create-home --home-dir ${USER_HOME} \
	--no-log-init ${USER}

RUN mkdir ${USER_HOME}/libs
RUN mkdir ${USER_HOME}/patches
RUN mkdir ${USER_HOME}/in_seq
RUN mkdir ${USER_HOME}/out_seq
RUN mkdir ${USER_HOME}/fault_seq
RUN mkdir ${USER_HOME}/webapps
RUN mkdir ${USER_HOME}/jaggeryapps

# copy the jdk and product packs
COPY ${FILES}/${WSO2_SERVER_PACK} ${STARTUP_SCRIPT} ${FILES}/${JDK_ARCHIVE} ${FILES}/${CLIENT_TRUSTSTORE} \
    ${FILES}/${WSO2CARBON_JKS} sudoers change_ownership.sh ${USER_HOME}/
COPY ${LIBS} ${USER_HOME}/libs/
COPY ${PATCHES} ${USER_HOME}/patches/
COPY ${IN_SEQ} ${USER_HOME}/in_seq/
COPY ${OUT_SEQ} ${USER_HOME}/out_seq/
COPY ${FAULT_SEQ} ${USER_HOME}/fault_seq/
COPY ${WEBAPPS} ${USER_HOME}/webapps/
COPY ${JAGGERYAPPS} ${USER_HOME}/jaggeryapps/

# and creates the init script
RUN unzip -q ${USER_HOME}/${WSO2_SERVER_PACK} -d ${USER_HOME}/ \
        && mkdir -p ${JAVA_HOME} \
        && tar -xf ${USER_HOME}/${JDK_ARCHIVE} -C ${JAVA_HOME} --strip-components=1 \
        && mkdir -p ${USER_HOME}/tmp \
        && cp ${USER_HOME}/${CLIENT_TRUSTSTORE} \
                    ${USER_HOME}/${WSO2_SERVER}-${WSO2_SERVER_VERSION}/repository/resources/security/ \
        && cp ${USER_HOME}/${WSO2CARBON_JKS} \
            ${USER_HOME}/${WSO2_SERVER}-${WSO2_SERVER_VERSION}/repository/resources/security/ \
        && cp ${USER_HOME}/libs/* ${USER_HOME}/${WSO2_SERVER}-${WSO2_SERVER_VERSION}/repository/components/lib/ \
	&& mkdir -p ${USER_HOME}/${WSO2_SERVER}-${WSO2_SERVER_VERSION}/repository/components/patches/${TARGET_PATCH_DIR} \
        && cp -r ${USER_HOME}/patches/* ${USER_HOME}/${WSO2_SERVER}-${WSO2_SERVER_VERSION}/repository/components/patches/${TARGET_PATCH_DIR} \
        && cp ${USER_HOME}/in_seq/* ${USER_HOME}/${WSO2_SERVER}-${WSO2_SERVER_VERSION}/repository/resources/customsequences/in/ \
        && cp ${USER_HOME}/out_seq/* ${USER_HOME}/${WSO2_SERVER}-${WSO2_SERVER_VERSION}/repository/resources/customsequences/out/ \
        && cp ${USER_HOME}/fault_seq/* ${USER_HOME}/${WSO2_SERVER}-${WSO2_SERVER_VERSION}/repository/resources/customsequences/fault/ \
        && cp ${USER_HOME}/webapps/* ${USER_HOME}/${WSO2_SERVER}-${WSO2_SERVER_VERSION}/repository/deployment/server/webapps \
        && rm -rf ${USER_HOME}/${WSO2_SERVER}-${WSO2_SERVER_VERSION}/repository/deployment/server/jaggeryapps/publisher \
        && rm -rf ${USER_HOME}/${WSO2_SERVER}-${WSO2_SERVER_VERSION}/repository/deployment/server/jaggeryapps/store \
        && unzip ${USER_HOME}/jaggeryapps/publisher.zip -d ${USER_HOME}/${WSO2_SERVER}-${WSO2_SERVER_VERSION}/repository/deployment/server/jaggeryapps/ \
        && unzip ${USER_HOME}/jaggeryapps/store.zip -d ${USER_HOME}/${WSO2_SERVER}-${WSO2_SERVER_VERSION}/repository/deployment/server/jaggeryapps/ \
        && rm -rf ${USER_HOME}/${WSO2_SERVER}-${WSO2_SERVER_VERSION}/repository/deployment/server/webapps/am#sample#calculator#v1 \
        && rm -rf ${USER_HOME}/${WSO2_SERVER}-${WSO2_SERVER_VERSION}/repository/deployment/server/webapps/am#sample#pizzashack#v1 \
        && rm -rf ${USER_HOME}/${WSO2_SERVER}-${WSO2_SERVER_VERSION}/repository/deployment/server/webapps/am#sample#calculator#v1.war \
        && rm -rf ${USER_HOME}/${WSO2_SERVER}-${WSO2_SERVER_VERSION}/repository/deployment/server/webapps/am#sample#pizzashack#v1.war \
        && cp -r ${USER_HOME}/${WSO2_SERVER}-${WSO2_SERVER_VERSION}/repository/deployment/server/synapse-configs ${USER_HOME}/tmp/ \
        && rm ${USER_HOME}/${WSO2_SERVER_PACK} \
        && rm ${USER_HOME}/${JDK_ARCHIVE} \
        && rm ${USER_HOME}/${CLIENT_TRUSTSTORE} \
        && rm ${USER_HOME}/${WSO2CARBON_JKS} \
        && rm -rf ${USER_HOME}/libs \
        && rm -rf ${USER_HOME}/patches \
        && rm -rf ${USER_HOME}/in_seq \
        && rm -rf ${USER_HOME}/out_seq \
        && rm -rf ${USER_HOME}/fault_seq \
        && rm -rf ${USER_HOME}/webapps \
        && rm -rf ${USER_HOME}/jaggeryapps \
	&& mkdir -p ${USER_HOME}/scripts/ \
	&& cat ${USER_HOME}/${STARTUP_SCRIPT} > ${USER_HOME}/scripts/${STARTUP_SCRIPT} \
	&& rm ${USER_HOME}/${STARTUP_SCRIPT} \
	&& cat ${USER_HOME}/sudoers > /etc/sudoers \
	&& rm ${USER_HOME}/sudoers \
	&& cat ${USER_HOME}/change_ownership.sh > /bin/change_ownership.sh \
	&& chmod 0755 /bin/change_ownership.sh \
	&& rm ${USER_HOME}/change_ownership.sh \
	&& chgrp -R 0 ${USER_HOME} \
	&& chmod -R g=u ${USER_HOME} \
	&& chown -R ${USER_ID} ${USER_HOME} \
	&& chmod -R 0774 ${USER_HOME}

# set the user, work directory and home 
USER ${USER_ID}
WORKDIR ${USER_HOME}

# set java home and path variables
ENV HOME=${USER_HOME} JAVA_HOME=${JAVA_HOME} PATH=$JAVA_HOME/bin:$PATH USER_HOME=${USER_HOME} \
        WSO2_SERVER=${WSO2_SERVER} WSO2_SERVER_VERSION=${WSO2_SERVER_VERSION} USER=${USER}

# expose ports
EXPOSE 8280 8243 9763 9443 5672 9711 9611 7711 7611

ENTRYPOINT exec ${USER_HOME}/scripts/init_carbon.sh
